substitutions:
  _PROJECT_ID: '$PROJECT_ID'
steps:
  #Build the container Image 
  # - name: "node"
  #   entrypoint: "bash"
  #   args:
  #   - -c
  #   - |
  #     echo $_PROJECT_ID 
  - name: 'gcr.io/cloud-builders/docker'
    args: ["build", "-t", "gcr.io/$_PROJECT_ID/node-app:$SHORT_SHA", "."]
  # pusth the repo to container registry 
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$_PROJECT_ID/node-app:$SHORT_SHA" ]
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
    - run 
    - --filename=k8s/deployment.yaml
    - --image="gcr.io/$_PROJECT_ID/node-app:$SHORT_SHA"
    - --location=us-central1
    - --cluster=k8s-cluster