substitutions:
  _PROJECT_ID: '$PROJECT_ID'
steps:
  #Build the container Image 
  - name: 'gcr.io/cloud-builders/docker'
    args: ["build", "-t", "gcr.io/$_PROJECT_ID/node-app:$SHORT_SHA", "."]
  # pusth the repo to container registry 
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$_PROJECT_ID/node-app:$SHORT_SHA" ]
  # Deploy containers to GKE
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
    - run 
    - --filename=k8s/deployment.yaml
    # Below line will replace the conatiner image in deployement file 
    - --image=gcr.io/$_PROJECT_ID/node-app:$SHORT_SHA 
    - --location=us-central1-a
    - --cluster=k8s-cluster