apiVersion: apps/v1
kind: Deployment
metadata:
  name:  node-app
spec:
  selector:
    matchLabels:
      app: node-app
  replicas: 1
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name:  node-app
        image:  $IMAGE_NAME
 
---
apiVersion: v1 
kind: Service
metadata:
  name: node-app-svc
spec:
  selector:
    app: node-app
  type: NodePort
  ports:
  - name: node-app
    port: 8080
    targetPort: 8080
