apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  selector:
    matchLabels:
      app: node-app
  replicas: 1
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          #image: gcr.io/gcp-training-377619/node-app
          image: us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0

---
apiVersion: v1
kind: Service
metadata:
  name: node-app-svc
spec:
  selector:
    app: node-app
  type: NodePort
  ports:
    - name: node-app
      port: 8080
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-gke-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: ingress-webapps
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: node-app-svc
            port:
              number: 8080
